# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: BYR BBS Crawler

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipreqs
        pipreqs .
        pip install -r requirements.txt
    - name: 'crawler'
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD_SESSION: ${{ secrets.PASSWORD_SESSION }}
        #下面这个不用管
        CALLBACK_URL: ${{ secrets.CALLBACK_URL }}
        ROOM_ID: ${{ secrets.ROOM_ID }}
      run: python auto.py
